<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="raktbeej" failures="1" tests="3" name="Test" time="14.831" errors="0" timestamp="2025-09-09T14:48:48 IST">
  <testcase classname="dataprovider.pack.dataprovider" name="testLogo" time="0.092"/>
  <testcase classname="dataprovider.pack.dataprovider" name="testAppUrl" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at dataprovider.pack.dataprovider.testAppUrl(dataprovider.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAppUrl -->
  <testcase classname="dataprovider.pack.dataprovider" name="testHomePageTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testHomePageTitle -->
</testsuite> <!-- Test -->
